### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by LYH6645** [baoguangsheng/g-transformer#14]
after training sent and doc models, i miss this error.
`Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/g-transformer/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dell/anaconda3/envs/g-transformer/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dell/桌面/g-transformer/fairseq_cli/generate.py", line 356, in <module>
    cli_main()
  File "/home/dell/桌面/g-transformer/fairseq_cli/generate.py", line 352, in cli_main
    main(args)
  File "/home/dell/桌面/g-transformer/fairseq_cli/generate.py", line 40, in main
    return _main(args, sys.stdout)
  File "/home/dell/桌面/g-transformer/fairseq_cli/generate.py", line 169, in _main
    hypos = task.inference_step(generator, models, sample, prefix_tokens)
  File "/home/dell/桌面/g-transformer/fairseq/tasks/fairseq_task.py", line 358, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/dell/anaconda3/envs/g-transformer/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/dell/桌面/g-transformer/fairseq/sequence_generator.py", line 176, in generate
    return self._generate(sample, **kwargs)
  File "/home/dell/桌面/g-transformer/fairseq/sequence_generator.py", line 331, in _generate
    _fill_frame(tokens, src_tokens)
  File "/home/dell/桌面/g-transformer/fairseq/sequence_generator.py", line 283, in _fill_frame
    docfrm = _align_frame(src[i])
  File "/home/dell/桌面/g-transformer/fairseq/sequence_generator.py", line 267, in _align_frame
    assert len(frame) % 3 == 0
AssertionError`

**Comment by baoguangsheng** [comment]
Which scripts are you running and on which dataset? The assertion error indicates that your source tokens may not be in correct format like "\<s\> sentence one \</s\> \<s\> sentence two \</s\> ...". Would you please check it or debug into code to dump the source tokens and the content in the frame variable? Thanks.

**Comment by LYH6645** [comment]
Thank you for your reply. I am training data using my own dataset on `G-Transformer fine tuned on send Transformer`, but I do not want to use federated dictionaries and BPE operations. Therefore, I have processed my data into the same format as in `europarl7-sent.segmented.en-de` and `europarl7-doc.segmented.en-de` For each sentence `<s> sentence </s>`, for each document `<s> sentence1 </s> <s> sentence2 </s>`, Then use `fairseq-process` to build the Glossary and generate binary files. Everything is normal until the inference stage. Then the above error occurred. and I was not aware of which link went wrong.

**Comment by baoguangsheng** [comment]
Your format is OK. I think the error is caused by the processing step, which should follow our scripts to call the updated fairseq_cli.preprocess. Otherwise, the \<s\> and \</s\> may not be reserved by the processing.
